### ISSUE TITLE
Support a db backend for high availability scenarios 

### ISSUE THREAD

**Issue by miraculixx** [corridor/configurable-http-proxy#9]
To enable running chp multiple times in a HA scenario it needs to support a database backend (instead of in-memory, as currently).

Requirements:

* implement `store.DatabaseStore` using sqlalchemy for max flexibility
* add tests
* make this an optional requirement, e.g. `pip install configurable-http-proxy[sqla]`

**Comment by AbdealiJK** [comment]
Hi @miraculixx That sounds like a cool idea.
I would be very open to merge a PR with this addition.

So I understand it better - does the current javascript based configurable-http-proxy have a database store already ?
Or how do you handle this with it with the current CHP ?
Trying to understand if this is a feature parity issue that should be documented in the README or is this a new request for the proxy which doesn't exist so far

**Comment by miraculixx** [comment]
> does the current javascript based configurable-http-proxy have a database store already 

Not directly, but it does have support for [pluggable storage](https://github.com/jupyterhub/configurable-http-proxy/pull/85) and there is a [Redis implementation](https://github.com/globocom/configurable-http-proxy-redis-backend). However, I need one that SQL based.
